nome = input('Digite deu nome completo: ')
print('-' * 60)
print('Seu nome é: {}'.format(nome))
print('Todas as letras em maiusculo: {}'.format(nome.upper()))
print('Todas as letras em minusculo: {}'.format(nome.lower()))
nn = nome.count(' ')
print('Quantidade de letras no seu nome completo: {}'.format(len(nome) - nn))
pn = nome.split()
print('Quantidade de letras no seu primeiro nome: {}'.format(len(pn[0])))
print('-' * 60)

#resolução do exercicio
nome = input('Digite deu nome completo: ').strip()
print('-' * 60)
print('Seu nome é: {}'.format(nome))
print('Todas as letras em maiusculo: {}'.format(nome.upper()))
print('Todas as letras em minusculo: {}'.format(nome.lower()))
print('Quantidade de letras no seu nome completo: {}'.format(len(nome) - nome.count(' ')))
print('Quantidade de letras no seu primeiro nome: {}'.format(nome.find(' ')))
print('-' * 60)
