n = int(input('Digite um numero qualquer e veja a sua tabuada: '))
print('A tabuada de mutiplicação de {}\n {:=^21} \n {} {} {} {} {} {} {} {} {} {} '.format(n, n, n*1, n*2, n*3, n*4, n*5, n*6, n*7, n*8, n*9, n*10))
print('A tabuada de divisao de {}\n {:=^21} \n {:.2f} {:.2f} {:.2f} {:.2f} {:.2f} {:.2f} {:.2f} {:.2f} {:.2f} {:.2f}'.format(n, n, n/1, n/2, n/3, n/4, n/5, n/6, n/7, n/8, n/9, n/10))
print('A tabuada de soma de {}\n {:=^21} \n {} {} {} {} {} {} {} {} {} {} '.format(n, n, n+1, n+2, n+3, n+4, n+5, n+6, n+7, n+8, n+9, n+10))
print('A tabuada de subtração de {}\n {:=^21} \n {} {} {} {} {} {} {} {} {} {} '.format(n, n, n-1, n-2, n-3, n-4, n-5, n-6, n-7, n-8, n-9, n-10))
print('-'*12)
print('{} x {:2} = {}'.format(n, 1, n*1))
print('{} x {:2} = {}'.format(n, 2, n*1))
print('{} x {:2} = {}'.format(n, 3, n*1))
print('{} x {:2} = {}'.format(n, 4, n*1))
print('{} x {:2} = {}'.format(n, 5, n*1))
print('{} x {:2} = {}'.format(n, 6, n*1))
print('{} x {:2} = {}'.format(n, 7, n*1))
print('{} x {:2} = {}'.format(n, 8, n*1))
print('{} x {:2} = {}'.format(n, 9, n*1))
print('{} x {:2} = {}'.format(n, 10, n*1))
print('-'*12)
