#tipos primitivos e saidas de dados/ exercicio 004
a1 = input('Digite algo: ')
a2 = int(input('Digite algo: '))
a3 = bool(input('Digite algo: '))
a4 = float(input('Digite algo: '))
print(type(a1))
print(type(a2))
print(type(a3))
print(type(a4))
print('É alpha numerico?', a1.isalnum())
print('É numerico?', a1.isnumeric())
print('É somente espaço?', a1.isspace())
print('É decimal?', a1.isdecimal())
print('Esta no diminutivo?', a1.islower())
print('Esta em maiuscula', a1.isupper())
print('Esta captalizado?', a1.istitle())
